# Generated by Django 2.2.5 on 2019-09-19 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='ftName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 13, 52, 27, 906449, tzinfo=utc)),
        ),
    ]
