# Generated by Django 2.2.3 on 2019-09-20 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_auto_20190920_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 11, 39, 56, 78218, tzinfo=utc)),
        ),
    ]
