# Generated by Django 2.2.5 on 2019-09-19 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_auto_20190919_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruckcomment',
            name='ftCommentftName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 15, 0, 1, 484561, tzinfo=utc)),
        ),
    ]
