# Generated by Django 2.2.5 on 2019-09-19 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0003_auto_20190919_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruckcomment',
            name='ftCommentftName',
        ),
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 15, 49, 24, 233103, tzinfo=utc)),
        ),
    ]
