# Generated by Django 2.2.3 on 2019-09-20 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0004_auto_20190920_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 11, 45, 57, 142590, tzinfo=utc)),
        ),
    ]
