# Generated by Django 2.2.5 on 2019-09-19 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0004_auto_20190919_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 15, 52, 47, 642264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftRating',
            field=models.PositiveIntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default='5', max_length=10),
        ),
    ]
