# Generated by Django 2.2.5 on 2019-09-19 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0005_auto_20190919_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='ftRating',
            field=models.FloatField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 17, 51, 26, 929301, tzinfo=utc)),
        ),
    ]
