# Generated by Django 2.2.3 on 2019-09-21 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0005_auto_20190920_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 21, 4, 5, 21, 54813, tzinfo=utc)),
        ),
    ]
