# Generated by Django 2.2.5 on 2019-09-21 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0007_auto_20190921_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 21, 5, 31, 57, 860904, tzinfo=utc)),
        ),
    ]
