# Generated by Django 2.2.3 on 2019-09-21 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0008_auto_20190921_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 21, 7, 26, 25, 283478, tzinfo=utc)),
        ),
    ]
