# Generated by Django 2.2.5 on 2019-09-20 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0008_auto_20190919_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 9, 50, 58, 441692, tzinfo=utc)),
        ),
    ]
