# Generated by Django 2.2.5 on 2019-09-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0009_auto_20190921_0726'),
        ('foodtruck', '0008_auto_20190921_1616'),
    ]

    operations = [
    ]
