# Generated by Django 2.2.5 on 2019-09-20 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0009_auto_20190920_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckcomment',
            name='ftCommentTimeStamp',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 11, 17, 5, 499088, tzinfo=utc)),
        ),
    ]
