# Generated by Django 2.2.5 on 2019-09-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='score2',
        ),
        migrations.AddField(
            model_name='myuser',
            name='insidescore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='songscore',
            field=models.IntegerField(default=0),
        ),
    ]
