# Generated by Django 2.2.5 on 2019-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190919_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='inside_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='song_done',
            field=models.BooleanField(default=False),
        ),
    ]
