# Generated by Django 2.2.5 on 2019-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190921_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='sun',
            field=models.IntegerField(default=0),
        ),
    ]
