# Generated by Django 2.2.5 on 2019-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190921_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fri',
            field=models.IntegerField(default=1),
        ),
    ]
