# Generated by Django 2.1.3 on 2019-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDay', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='mon', max_length=100)),
                ('eventImage', models.ImageField(blank=True, upload_to='images/')),
                ('eventContent', models.CharField(max_length=300)),
                ('eventTitle', models.CharField(max_length=200)),
                ('when', models.CharField(default='', max_length=200)),
                ('where', models.CharField(default='', max_length=200)),
                ('what', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
