# Generated by Django 2.2.5 on 2019-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventImage', models.ImageField(blank=True, upload_to='images/')),
                ('eventContent', models.CharField(max_length=300)),
                ('eventTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
