# Generated by Django 2.2.3 on 2019-09-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190920_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='eventImage',
            field=models.ImageField(blank=True, upload_to='../images/'),
        ),
    ]
