# Generated by Django 2.2.5 on 2019-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_eventday'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='what',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='when',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='where',
            field=models.CharField(default='', max_length=200),
        ),
    ]
