# Generated by Django 2.2.3 on 2019-09-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190921_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='eventImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
