# Generated by Django 2.2.5 on 2019-09-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190921_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='eventImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
