# Generated by Django 2.2.3 on 2019-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madang', '0002_madang_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='jooho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
