# Generated by Django 2.2.3 on 2019-09-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madang', '0003_jooho'),
    ]

    operations = [
        migrations.AddField(
            model_name='madang',
            name='contents',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madang',
            name='detail',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='madang',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='madang',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
