# Generated by Django 2.2.3 on 2019-09-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madang', '0004_auto_20190918_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madang',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=100),
        ),
    ]
