# Generated by Django 2.2.5 on 2019-09-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madang', '0005_auto_20190920_0448'),
        ('madang', '0005_auto_20190920_0950'),
    ]

    operations = [
    ]
